import sys
import os
import json
import socket
import time

sys.path.insert(0, ".")

from gis_service import verify_gis_location, parse_dimensions_from_text, get_local_dataset
from web_app import render_gis_section

print("==================================================")
print("FINAL END-TO-END APPLICATION PIPELINE & UI VALIDATION")
print("==================================================")

# 1. Realistic OCR output schema generated by land_document_extractor.py
ocr_output_karnataka = {
    "document_type": "Sale Deed",
    "state": "Karnataka",
    "property": {
        "state": "Karnataka",
        "district": "Mandya",
        "taluk": "Nagamangala",
        "village": "Devalapura",
        "survey_number": "142/3A",
        "dimensions": "East-West 60 ft, North-South 40 ft"
    }
}

# 2. Run GIS Resolution Pipeline
t0 = time.time()
gis_res_ka = verify_gis_location(ocr_output_karnataka)
t_gis = time.time() - t0

print(f"\n1. GIS Resolution Execution Time: {t_gis:.4f}s")
print("   - Status:", gis_res_ka["status"])
print("   - Resolution Level:", gis_res_ka["resolution_level"])
print("   - Village Status:", gis_res_ka["village_status"])
print("   - Coordinates:", gis_res_ka["coordinates"])
print("   - Confidence:", gis_res_ka["gis_resolution_confidence"])
print("   - Source Dataset:", gis_res_ka["source_dataset"])
print("   - Dimensions Info:", gis_res_ka.get("dimensions"))

# 3. Test Web App UI HTML Rendering
t1 = time.time()
ui_html = render_gis_section(gis_res_ka)
t_ui = time.time() - t1

print(f"\n2. UI Card & Leaflet Map HTML Generation Time: {t_ui*1000:.2f} ms")
print("   - UI HTML Output Length:", len(ui_html), "bytes")
print("   - Contains Leaflet Map Canvas (#gis-map-leaflet)?:", "gis-map-leaflet" in ui_html)
print("   - Contains Administrative Polygon Layer?:", "adminLayer" in ui_html or "L.geoJSON" in ui_html)
print("   - Contains Estimated Parcel Layer?:", "parcelLayer" in ui_html or "estimated_parcel_polygon" in ui_html or "L.polygon" in ui_html)
print("   - Contains Disclaimers & Legend?:", "Estimated Parcel Boundary" in ui_html and "Village boundary shown from source GIS data" in ui_html)

# 4. Test Telangana Safety
ocr_output_telangana = {
    "state": "Telangana",
    "property": {
        "state": "Telangana",
        "district": "Sangareddy",
        "mandal": "Kandi",
        "village": "Kandi"
    }
}
gis_res_ts = verify_gis_location(ocr_output_telangana)
print("\n3. Telangana Safety Result:")
print("   - Status:", gis_res_ts["status"])
print("   - Resolution Level:", gis_res_ts["resolution_level"])
print("   - Village Status:", gis_res_ts["village_status"])
print("   - Disclaimer:", gis_res_ts.get("village_disclaimer"))

# 5. Offline Network Independence Test
print("\n4. Socket Blocking (Offline Independence) Test:")
orig_socket = socket.socket
try:
    socket.socket = None
    offline_res = verify_gis_location(ocr_output_karnataka)
    print("   - Offline Resolution Result:", offline_res["status"], offline_res["resolution_level"])
finally:
    socket.socket = orig_socket

print("\nE2E Pipeline & UI Validation Completed Successfully!")
